name = "SDMX"
uuid = "dab8ebd6-0c04-4f46-ad10-062f8ec9cad9"
authors = ["lsaenzt <59137624+lsaenzt@users.noreply.github.com>"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.6"
JSON3 = "1.9"
OrderedCollections = "1.4"
PrettyTables = "1.2"
Tables = "1.6"
